export const transactionsTestData = [
  {
    id: 1,
    dateAndTime: "22.07.2024 23:52:02",
    employee: "Алексей Подмасков",
    userLogin: "Silent",
    paymentMethod: "Наличные",
    amount: 2189,
    transactionDetails: 4,
    positionsProduct: [
      {
        id: 1,
        name: "Coca-Cola",
        price: 2189,
        pieceCount: 1,
        type: "product",
      },
      {
        id: 2,
        name: "Sprite",
        price: 2189,
        pieceCount: 1,
        type: "product",
      },
      {
        id: 3,
        name: "Ayran",
        price: 2189,
        pieceCount: 1,
        type: "product",
      },
    ],
    transactionID: "36765ffsFD657df",
    transactionStatus: "Оплачено",
  },
  {
    id: 2,
    dateAndTime: "22.07.2024 23:52:02",
    employee: "Алексей Подмасков",
    userLogin: "Silent",
    paymentMethod: "Наличные",
    amount: 2189,
    transactionDetails: 4,
    positionsProduct: [
      {
        id: 1,
        name: "Coca-Cola",
        price: 2189,
        pieceCount: 1,
        type: "product",
      },
      {
        id: 2,
        name: "Sprite",
        price: 2189,
        pieceCount: 1,
        type: "product",
      },
      {
        id: 3,
        name: "Ayran",
        price: 2189,
        pieceCount: 1,
        type: "product",
      },
    ],
    transactionID: "36765ffsFD657df",
    transactionStatus: "Оплачено",
  },
  {
    id: 3,
    dateAndTime: "22.07.2024 23:52:02",
    employee: "Алексей Подмасков",
    userLogin: "Silent",
    paymentMethod: "Наличные",
    amount: 2189,
    transactionDetails: 4,
    positionsProduct: [
      {
        id: 1,
        name: "Coca-Cola",
        price: 2189,
        pieceCount: 1,
        type: "product",
      },
      {
        id: 2,
        name: "Sprite",
        price: 2189,
        pieceCount: 1,
        type: "product",
      },
      {
        id: 3,
        name: "Ayran",
        price: 2189,
        pieceCount: 1,
        type: "product",
      },
    ],
    transactionID: "36765ffsFD657df",
    transactionStatus: "Оплачено",
  },
];
