export const transactionsTestData = [
  {
    id: 1,
    dateAndTime: "22.07.2024 23:52:02",
    employee: "Алексей Подмасков",
    userLogin: "Silent",
    paymentMethod: "Наличные",
    amount: 2189,
    transactionDetails: 4,
    transactionID: "36765ffsFD657df",
    transactionStatus: "Оплачено",
  },
  {
    id: 2,
    dateAndTime: "22.07.2024 23:52:02",
    employee: "Алексей Подмасков",
    userLogin: "Silent",
    paymentMethod: "Наличные",
    amount: 2189,
    transactionDetails: 4,
    transactionID: "36765ffsFD657df",
    transactionStatus: "Оплачено",
  },
  {
    id: 3,
    dateAndTime: "22.07.2024 23:52:02",
    employee: "Алексей Подмасков",
    userLogin: "Silent",
    paymentMethod: "Наличные",
    amount: 2189,
    transactionDetails: 4,
    transactionID: "36765ffsFD657df",
    transactionStatus: "Оплачено",
  },
];
